### ISSUE TITLE
bellevue_pretrained_models.tar.gz is missing

### ISSUE THREAD

**Issue by fzhiy** [edge-video-services/ekya#5]
Hi, thank you very much for this great work. 
The **bellevue_pretrained_models.tar.gz** in the section Running Ekya with Urban Traffic Dataset is missing, can you please provide this pre-trained model? Thank you!

**Comment by xlcbingo1999** [comment]
I meet the same problem. Have you solved it?

**Comment by romilbhardwaj** [comment]
Thanks for your interest. `bellevue_pretrained_models.tar.gz ` is available here - https://drive.google.com/file/d/1fZHb3CwRqMVBWn_VmBBC6Rd-R5aJ8M3t/view?usp=drive_link
